# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@rowtype-yoga/prettier-plugin-purescript-1.11.2" = {
      name = "_at_rowtype-yoga_slash_prettier-plugin-purescript";
      packageName = "@rowtype-yoga/prettier-plugin-purescript";
      version = "1.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rowtype-yoga/prettier-plugin-purescript/-/prettier-plugin-purescript-1.11.2.tgz";
        sha512 = "9G66e0cF+OB5wzX4SZKV8/gsAOkxJsuIUXeiNrzstEbc/a7aI4LT+ho+Tkz3JBkNCtvz9Z5GPL50WLaq1XGLPQ==";
      };
    };
    "@types/node-16.18.14" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "16.18.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-16.18.14.tgz";
        sha512 = "wvzClDGQXOCVNU4APPopC2KtMYukaF1MN/W3xAmslx22Z4/IF1/izDMekuyoUlwfnDHYCIZGaj7jMwnJKBTxKw==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "available-typed-arrays-1.0.5" = {
      name = "available-typed-arrays";
      packageName = "available-typed-arrays";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/available-typed-arrays/-/available-typed-arrays-1.0.5.tgz";
        sha512 = "DMD0KiN46eipeziST1LPP/STfDU0sufISXmjSgvVsoU2tqxctQeASejWcfNtxYKqETM1UxQ8sp2OrSBWpHY6sw==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "call-bind-1.0.2" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.2.tgz";
        sha512 = "7O+FbCihrB5WGbFYesctwmTKae6rOiIzmz1icreWJ+0aA7LJfuqhEso2T9ncpcFtzMQtzXf2QGGueWJGTYsqrA==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha512 = "72fSenhMw2HZMTVHeCA9KCmpEIbzWiQsjN+BHcBbS9vr1mtt+vJjPdksIBNUmKAW8TFUDPJK5SUU3QhE9NEXDw==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "cross-spawn-6.0.5" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "6.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-6.0.5.tgz";
        sha512 = "eTVLrBSt7fjbDygz805pMnstIs2VTBNkRm0qxZd+M7A5XDdxVRWO5MxGBXZhjY4cqLYLdtrGqRf8mBPmzwSpWQ==";
      };
    };
    "define-properties-1.2.0" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.2.0.tgz";
        sha512 = "xvqAVKGfT1+UAvPwKTVw/njhdQ8ZhXK4lI0bCIuCMrp2up9nPnaDftrLtmpTazqd1o+UY4zgzU+avtMbDP+ldA==";
      };
    };
    "error-ex-1.3.2" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz";
        sha512 = "7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==";
      };
    };
    "es-abstract-1.21.1" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.21.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.21.1.tgz";
        sha512 = "QudMsPOz86xYz/1dG1OuGBKOELjCh99IIWHLzy5znUB6j8xG2yMA7bfTV86VSqKF+Y/H08vQPR+9jyXpuC6hfg==";
      };
    };
    "es-set-tostringtag-2.0.1" = {
      name = "es-set-tostringtag";
      packageName = "es-set-tostringtag";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-set-tostringtag/-/es-set-tostringtag-2.0.1.tgz";
        sha512 = "g3OMbtlwY3QewlqAiMLI47KywjWZoEytKr8pf6iTC8uJq5bIAH52Z9pnQ8pVL6whrCto53JZDuUIsifGeLorTg==";
      };
    };
    "es-to-primitive-1.2.1" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.1.tgz";
        sha512 = "QCOllgZJtaUo9miYBcLChTUaHNjJF3PYs1VidD7AwiEj1kYxKeQTctLAezAOH5ZKRH0g2IgPn6KwB4IT8iRpvA==";
      };
    };
    "esbuild-0.13.15" = {
      name = "esbuild";
      packageName = "esbuild";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild/-/esbuild-0.13.15.tgz";
        sha512 = "raCxt02HBKv8RJxE8vkTSCXGIyKHdEdGfUmiYb8wnabnaEmHzyW7DCHb5tEN0xU8ryqg5xw54mcwnYkC4x3AIw==";
      };
    };
    "esbuild-android-arm64-0.13.15" = {
      name = "esbuild-android-arm64";
      packageName = "esbuild-android-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-android-arm64/-/esbuild-android-arm64-0.13.15.tgz";
        sha512 = "m602nft/XXeO8YQPUDVoHfjyRVPdPgjyyXOxZ44MK/agewFFkPa8tUo6lAzSWh5Ui5PB4KR9UIFTSBKh/RrCmg==";
      };
    };
    "esbuild-darwin-64-0.13.15" = {
      name = "esbuild-darwin-64";
      packageName = "esbuild-darwin-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-64/-/esbuild-darwin-64-0.13.15.tgz";
        sha512 = "ihOQRGs2yyp7t5bArCwnvn2Atr6X4axqPpEdCFPVp7iUj4cVSdisgvEKdNR7yH3JDjW6aQDw40iQFoTqejqxvQ==";
      };
    };
    "esbuild-darwin-arm64-0.13.15" = {
      name = "esbuild-darwin-arm64";
      packageName = "esbuild-darwin-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-arm64/-/esbuild-darwin-arm64-0.13.15.tgz";
        sha512 = "i1FZssTVxUqNlJ6cBTj5YQj4imWy3m49RZRnHhLpefFIh0To05ow9DTrXROTE1urGTQCloFUXTX8QfGJy1P8dQ==";
      };
    };
    "esbuild-freebsd-64-0.13.15" = {
      name = "esbuild-freebsd-64";
      packageName = "esbuild-freebsd-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-64/-/esbuild-freebsd-64-0.13.15.tgz";
        sha512 = "G3dLBXUI6lC6Z09/x+WtXBXbOYQZ0E8TDBqvn7aMaOCzryJs8LyVXKY4CPnHFXZAbSwkCbqiPuSQ1+HhrNk7EA==";
      };
    };
    "esbuild-freebsd-arm64-0.13.15" = {
      name = "esbuild-freebsd-arm64";
      packageName = "esbuild-freebsd-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-arm64/-/esbuild-freebsd-arm64-0.13.15.tgz";
        sha512 = "KJx0fzEDf1uhNOZQStV4ujg30WlnwqUASaGSFPhznLM/bbheu9HhqZ6mJJZM32lkyfGJikw0jg7v3S0oAvtvQQ==";
      };
    };
    "esbuild-linux-32-0.13.15" = {
      name = "esbuild-linux-32";
      packageName = "esbuild-linux-32";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-32/-/esbuild-linux-32-0.13.15.tgz";
        sha512 = "ZvTBPk0YWCLMCXiFmD5EUtB30zIPvC5Itxz0mdTu/xZBbbHJftQgLWY49wEPSn2T/TxahYCRDWun5smRa0Tu+g==";
      };
    };
    "esbuild-linux-64-0.13.15" = {
      name = "esbuild-linux-64";
      packageName = "esbuild-linux-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.13.15.tgz";
        sha512 = "eCKzkNSLywNeQTRBxJRQ0jxRCl2YWdMB3+PkWFo2BBQYC5mISLIVIjThNtn6HUNqua1pnvgP5xX0nHbZbPj5oA==";
      };
    };
    "esbuild-linux-arm-0.13.15" = {
      name = "esbuild-linux-arm";
      packageName = "esbuild-linux-arm";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm/-/esbuild-linux-arm-0.13.15.tgz";
        sha512 = "wUHttDi/ol0tD8ZgUMDH8Ef7IbDX+/UsWJOXaAyTdkT7Yy9ZBqPg8bgB/Dn3CZ9SBpNieozrPRHm0BGww7W/jA==";
      };
    };
    "esbuild-linux-arm64-0.13.15" = {
      name = "esbuild-linux-arm64";
      packageName = "esbuild-linux-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm64/-/esbuild-linux-arm64-0.13.15.tgz";
        sha512 = "bYpuUlN6qYU9slzr/ltyLTR9YTBS7qUDymO8SV7kjeNext61OdmqFAzuVZom+OLW1HPHseBfJ/JfdSlx8oTUoA==";
      };
    };
    "esbuild-linux-mips64le-0.13.15" = {
      name = "esbuild-linux-mips64le";
      packageName = "esbuild-linux-mips64le";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-mips64le/-/esbuild-linux-mips64le-0.13.15.tgz";
        sha512 = "KlVjIG828uFPyJkO/8gKwy9RbXhCEUeFsCGOJBepUlpa7G8/SeZgncUEz/tOOUJTcWMTmFMtdd3GElGyAtbSWg==";
      };
    };
    "esbuild-linux-ppc64le-0.13.15" = {
      name = "esbuild-linux-ppc64le";
      packageName = "esbuild-linux-ppc64le";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-ppc64le/-/esbuild-linux-ppc64le-0.13.15.tgz";
        sha512 = "h6gYF+OsaqEuBjeesTBtUPw0bmiDu7eAeuc2OEH9S6mV9/jPhPdhOWzdeshb0BskRZxPhxPOjqZ+/OqLcxQwEQ==";
      };
    };
    "esbuild-netbsd-64-0.13.15" = {
      name = "esbuild-netbsd-64";
      packageName = "esbuild-netbsd-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-netbsd-64/-/esbuild-netbsd-64-0.13.15.tgz";
        sha512 = "3+yE9emwoevLMyvu+iR3rsa+Xwhie7ZEHMGDQ6dkqP/ndFzRHkobHUKTe+NCApSqG5ce2z4rFu+NX/UHnxlh3w==";
      };
    };
    "esbuild-openbsd-64-0.13.15" = {
      name = "esbuild-openbsd-64";
      packageName = "esbuild-openbsd-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-openbsd-64/-/esbuild-openbsd-64-0.13.15.tgz";
        sha512 = "wTfvtwYJYAFL1fSs8yHIdf5GEE4NkbtbXtjLWjM3Cw8mmQKqsg8kTiqJ9NJQe5NX/5Qlo7Xd9r1yKMMkHllp5g==";
      };
    };
    "esbuild-sunos-64-0.13.15" = {
      name = "esbuild-sunos-64";
      packageName = "esbuild-sunos-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-sunos-64/-/esbuild-sunos-64-0.13.15.tgz";
        sha512 = "lbivT9Bx3t1iWWrSnGyBP9ODriEvWDRiweAs69vI+miJoeKwHWOComSRukttbuzjZ8r1q0mQJ8Z7yUsDJ3hKdw==";
      };
    };
    "esbuild-windows-32-0.13.15" = {
      name = "esbuild-windows-32";
      packageName = "esbuild-windows-32";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-32/-/esbuild-windows-32-0.13.15.tgz";
        sha512 = "fDMEf2g3SsJ599MBr50cY5ve5lP1wyVwTe6aLJsM01KtxyKkB4UT+fc5MXQFn3RLrAIAZOG+tHC+yXObpSn7Nw==";
      };
    };
    "esbuild-windows-64-0.13.15" = {
      name = "esbuild-windows-64";
      packageName = "esbuild-windows-64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.13.15.tgz";
        sha512 = "9aMsPRGDWCd3bGjUIKG/ZOJPKsiztlxl/Q3C1XDswO6eNX/Jtwu4M+jb6YDH9hRSUflQWX0XKAfWzgy5Wk54JQ==";
      };
    };
    "esbuild-windows-arm64-0.13.15" = {
      name = "esbuild-windows-arm64";
      packageName = "esbuild-windows-arm64";
      version = "0.13.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-arm64/-/esbuild-windows-arm64-0.13.15.tgz";
        sha512 = "zzvyCVVpbwQQATaf3IG8mu1IwGEiDxKkYUdA4FpoCHi1KtPa13jeScYDjlW0Qh+ebWzpKfR2ZwvqAQkSWNcKjA==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha512 = "vbRorB5FUQWvla16U8R/qgaFIya2qGzwDrNmCZuYKrbdSUMG6I1ZCGQRefkRVhuOkIGVne7BQ35DSfo1qvJqFg==";
      };
    };
    "for-each-0.3.3" = {
      name = "for-each";
      packageName = "for-each";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-each/-/for-each-0.3.3.tgz";
        sha512 = "jqYfLp7mo9vIyQf8ykW2v7A+2N4QjeCeI5+Dz9XraiO1ign81wjiH7Fb9vSOWvQfNtmSa4H2RoQTrrXivdUZmw==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "function.prototype.name-1.1.5" = {
      name = "function.prototype.name";
      packageName = "function.prototype.name";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/function.prototype.name/-/function.prototype.name-1.1.5.tgz";
        sha512 = "uN7m/BzVKQnCUF/iW8jYea67v++2u7m5UgENbHRtdDVclOUP+FMPlCNdmk0h/ysGyo2tavMJEDqJAkJdRa1vMA==";
      };
    };
    "functions-have-names-1.2.3" = {
      name = "functions-have-names";
      packageName = "functions-have-names";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/functions-have-names/-/functions-have-names-1.2.3.tgz";
        sha512 = "xckBUXyTIqT97tq2x2AMb+g163b5JFysYk0x4qxNFwbfQkmNZoiRHb6sPzI9/QV33WeuvVYBUIiD4NzNIyqaRQ==";
      };
    };
    "get-intrinsic-1.2.0" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.2.0.tgz";
        sha512 = "L049y6nFOuom5wGyRc3/gdTLO94dySVKRACj1RmJZBQXlbTMhtNIgkWkUHq+jYmZvKf14EW1EoJnnjbmoHij0Q==";
      };
    };
    "get-symbol-description-1.0.0" = {
      name = "get-symbol-description";
      packageName = "get-symbol-description";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-symbol-description/-/get-symbol-description-1.0.0.tgz";
        sha512 = "2EmdH1YvIQiZpltCNgkuiUnyukzxM/R6NDJX31Ke3BG1Nq5b0S2PhX59UKi9vZpPDQVdqn+1IcaAwnzTT5vCjw==";
      };
    };
    "globalthis-1.0.3" = {
      name = "globalthis";
      packageName = "globalthis";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/globalthis/-/globalthis-1.0.3.tgz";
        sha512 = "sFdI5LyBiNTHjRd7cGPWapiHWMOXKyuBNX/cWJ3NfzrZQVa8GI/8cofCl74AOVqq9W5kNmguTIzJ/1s2gyI9wA==";
      };
    };
    "gopd-1.0.1" = {
      name = "gopd";
      packageName = "gopd";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/gopd/-/gopd-1.0.1.tgz";
        sha512 = "d65bNlIadxvpb/A2abVdlqKqV563juRnZ1Wtk6s1sIR8uNsXR70xqIzVqxVf1eTqDunwT2MkczEeaezCKTZhwA==";
      };
    };
    "graceful-fs-4.2.10" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.10.tgz";
        sha512 = "9ByhssR2fPVsNZj478qUUbKfmL0+t5BDVyjShtyZZLiK7ZDAArFFfopyOTj0M05wE2tJPisA4iTnnXl2YoPvOA==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-bigints-1.0.2" = {
      name = "has-bigints";
      packageName = "has-bigints";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-bigints/-/has-bigints-1.0.2.tgz";
        sha512 = "tSvCKtBr9lkF0Ex0aQiP9N+OpV4zi2r/Nee5VkRDbaqv35RLYMzbwQfFSZZH0kR+Rd6302UJZ2p/bJCEoR3VoQ==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha512 = "sKJf1+ceQBr4SMkvQnBDNDtf4TXpVhVGateu0t918bl30FnbE2m4vNLX+VWe/dpjlb+HugGYzW7uQXH98HPEYw==";
      };
    };
    "has-property-descriptors-1.0.0" = {
      name = "has-property-descriptors";
      packageName = "has-property-descriptors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-property-descriptors/-/has-property-descriptors-1.0.0.tgz";
        sha512 = "62DVLZGoiEBDHQyqG4w9xCuZ7eJEwNmJRWw2VY84Oedb7WFcA27fiEVe8oUQx9hAUJ4ekurquucTGwsyO1XGdQ==";
      };
    };
    "has-proto-1.0.1" = {
      name = "has-proto";
      packageName = "has-proto";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-proto/-/has-proto-1.0.1.tgz";
        sha512 = "7qE+iP+O+bgF9clE5+UoBFzE65mlBiVj3tKCrlNQ0Ogwm0BjpT/gK4SlLYDMybDh5I3TCTKnPPa0oMG7JDYrhg==";
      };
    };
    "has-symbols-1.0.3" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.3.tgz";
        sha512 = "l3LCuF6MgDNwTDKkdYGEihYjt5pRPbEg46rtlmnSPlUbgmB8LOIrKJbYYFBSbnPaJexMKtiPO8hmeRjRz2Td+A==";
      };
    };
    "has-tostringtag-1.0.0" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.0.tgz";
        sha512 = "kFjcSNhnlGV1kyoGk7OXKSawH5JOb/LzUc5w9B02hOTO0dfFRjbHQKvg1d6cf3HbeUmtU9VbbV3qzZ2Teh97WQ==";
      };
    };
    "hosted-git-info-2.8.9" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "2.8.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.8.9.tgz";
        sha512 = "mxIDAb9Lsm6DoOJ7xH+5+X4y1LU/4Hi50L9C5sIswK3JzULS4bwk1FvjdBgvYR4bzT4tuUQiC15FE2f5HbLvYw==";
      };
    };
    "internal-slot-1.0.5" = {
      name = "internal-slot";
      packageName = "internal-slot";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/internal-slot/-/internal-slot-1.0.5.tgz";
        sha512 = "Y+R5hJrzs52QCG2laLn4udYVnxsfny9CpOhNhUvk/SSSVyF6T27FzRbF0sroPidSu3X8oEAkOn2K804mjpt6UQ==";
      };
    };
    "is-array-buffer-3.0.2" = {
      name = "is-array-buffer";
      packageName = "is-array-buffer";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-array-buffer/-/is-array-buffer-3.0.2.tgz";
        sha512 = "y+FyyR/w8vfIRq4eQcM1EYgSTnmHXPqaF+IgzgraytCFq5Xh8lllDVmAZolPJiZttZLeFSINPYMaEJ7/vWUa1w==";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha512 = "zz06S8t0ozoDXMG+ube26zeCTNXcKIPJZJi8hBrF4idCLms4CG9QtK7qBl1boi5ODzFpjswb5JPmHCbMpjaYzg==";
      };
    };
    "is-bigint-1.0.4" = {
      name = "is-bigint";
      packageName = "is-bigint";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-bigint/-/is-bigint-1.0.4.tgz";
        sha512 = "zB9CruMamjym81i2JZ3UMn54PKGsQzsJeo6xvN3HJJ4CAsQNB6iRutp2To77OfCNuoxspsIhzaPoO1zyCEhFOg==";
      };
    };
    "is-boolean-object-1.1.2" = {
      name = "is-boolean-object";
      packageName = "is-boolean-object";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-boolean-object/-/is-boolean-object-1.1.2.tgz";
        sha512 = "gDYaKHJmnj4aWxyj6YHyXVpdQawtVLHU5cb+eztPGczf6cjuTdwve5ZIEfgXqH4e57An1D1AKf8CZ3kYrQRqYA==";
      };
    };
    "is-callable-1.2.7" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.2.7.tgz";
        sha512 = "1BC0BVFhS/p0qtw6enp8e+8OD0UrK0oFLztSjNzhcKA3WDuJxxAPXzPuPtKkjEY9UUoEWlX/8fgKeu2S8i9JTA==";
      };
    };
    "is-core-module-2.11.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.11.0.tgz";
        sha512 = "RRjxlvLDkD1YJwDbroBHMb+cukurkDWNyHx7D3oNB5x9rb5ogcksMC5wHCadcXoo67gVr/+3GFySh3134zi6rw==";
      };
    };
    "is-date-object-1.0.5" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.5.tgz";
        sha512 = "9YQaSxsAiSwcvS33MBk3wTCVnWK+HhF8VZR2jRxehM16QcVOdHqPn4VPHmRK4lSr38n9JriurInLcP90xsYNfQ==";
      };
    };
    "is-negative-zero-2.0.2" = {
      name = "is-negative-zero";
      packageName = "is-negative-zero";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-negative-zero/-/is-negative-zero-2.0.2.tgz";
        sha512 = "dqJvarLawXsFbNDeJW7zAz8ItJ9cd28YufuuFzh0G8pNHjJMnY08Dv7sYX2uF5UpQOwieAeOExEYAWWfu7ZZUA==";
      };
    };
    "is-number-object-1.0.7" = {
      name = "is-number-object";
      packageName = "is-number-object";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number-object/-/is-number-object-1.0.7.tgz";
        sha512 = "k1U0IRzLMo7ZlYIfzRu23Oh6MiIFasgpb9X76eqfFZAqwH44UI4KTBvBYIZ1dSL9ZzChTB9ShHfLkR4pdW5krQ==";
      };
    };
    "is-regex-1.1.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.4.tgz";
        sha512 = "kvRdxDsxZjhzUX07ZnLydzS1TU/TJlTUHHY4YLL87e37oUA49DfkLqgy+VjFocowy29cKvcSiu+kIv728jTTVg==";
      };
    };
    "is-shared-array-buffer-1.0.2" = {
      name = "is-shared-array-buffer";
      packageName = "is-shared-array-buffer";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-shared-array-buffer/-/is-shared-array-buffer-1.0.2.tgz";
        sha512 = "sqN2UDu1/0y6uvXyStCOzyhAjCSlHceFoMKJW8W9EU9cvic/QdsZ0kEU93HEy3IUEFZIiH/3w+AH/UQbPHNdhA==";
      };
    };
    "is-string-1.0.7" = {
      name = "is-string";
      packageName = "is-string";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-string/-/is-string-1.0.7.tgz";
        sha512 = "tE2UXzivje6ofPW7l23cjDOMa09gb7xlAqG6jG5ej6uPV32TlWP3NKPigtaGeHNu9fohccRYvIiZMfOOnOYUtg==";
      };
    };
    "is-symbol-1.0.4" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.4.tgz";
        sha512 = "C/CPBqKWnvdcxqIARxyOh4v1UUEOCHpgDa0WYgpKDFMszcrPcffg5uhwSgPCLD2WWxmq6isisz87tzT01tuGhg==";
      };
    };
    "is-typed-array-1.1.10" = {
      name = "is-typed-array";
      packageName = "is-typed-array";
      version = "1.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typed-array/-/is-typed-array-1.1.10.tgz";
        sha512 = "PJqgEHiWZvMpaFZ3uTc8kHPM4+4ADTlDniuQL7cU/UDA0Ql7F70yGfHph3cLNe+c9toaigv+DFzTJKhc2CtO6A==";
      };
    };
    "is-weakref-1.0.2" = {
      name = "is-weakref";
      packageName = "is-weakref";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-weakref/-/is-weakref-1.0.2.tgz";
        sha512 = "qctsuLZmIQ0+vSSMfoVvyFe2+GSEvnmZ2ezTup1SBse9+twCCeial6EEi3Nc2KFcf6+qz2FBPnjXsk8xhKSaPQ==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "json-parse-better-errors-1.0.2" = {
      name = "json-parse-better-errors";
      packageName = "json-parse-better-errors";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-better-errors/-/json-parse-better-errors-1.0.2.tgz";
        sha512 = "mrqyZKfX5EhL7hvqcV6WG1yYjnjeuYDzDhhcAAUrq8Po85NBQBJP+ZDUT75qZQ98IkUoBqdkExkukOU7Ts2wrw==";
      };
    };
    "load-json-file-4.0.0" = {
      name = "load-json-file";
      packageName = "load-json-file";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-json-file/-/load-json-file-4.0.0.tgz";
        sha512 = "Kx8hMakjX03tiGTLAIdJ+lL0htKnXjEZN6hk/tozf/WOuYGdZBJrZ+rCJRbVCugsjB3jMLn9746NsQIf5VjBMw==";
      };
    };
    "memorystream-0.3.1" = {
      name = "memorystream";
      packageName = "memorystream";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/memorystream/-/memorystream-0.3.1.tgz";
        sha512 = "S3UwM3yj5mtUSEfP41UZmt/0SCoVYUcU1rkXv+BQ5Ig8ndL4sPoJNBUJERafdPb5jjHJGuMgytgKvKIf58XNBw==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "nice-try-1.0.5" = {
      name = "nice-try";
      packageName = "nice-try";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/nice-try/-/nice-try-1.0.5.tgz";
        sha512 = "1nh45deeb5olNY7eX82BkPO7SSxR5SSYJiPTrTdFUVYwAl8CKMA5N9PjTYkHiRjisVcxcQ1HXdLhx2qxxJzLNQ==";
      };
    };
    "normalize-package-data-2.5.0" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.5.0.tgz";
        sha512 = "/5CMN3T0R4XTj4DcGaexo+roZSdSFW/0AOOTROrjxzCG1wrWXEsGbRKevjlIL+ZDE4sZlJr5ED4YW0yqmkK+eA==";
      };
    };
    "npm-run-all-4.1.5" = {
      name = "npm-run-all";
      packageName = "npm-run-all";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-all/-/npm-run-all-4.1.5.tgz";
        sha512 = "Oo82gJDAVcaMdi3nuoKFavkIHBRVqQ1qvMb+9LHk/cF4P6B2m8aP04hGf7oL6wZ9BuGwX1onlLhpuoofSyoQDQ==";
      };
    };
    "object-inspect-1.12.3" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.12.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.12.3.tgz";
        sha512 = "geUvdk7c+eizMNUDkRpW1wJwgfOiOeHbxBR/hLXK1aT6zmVSO0jsQcs7fj6MGw89jC/cjGfLcNOrtMYtGqm81g==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.assign-4.1.4" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.4.tgz";
        sha512 = "1mxKf0e58bvyjSCtKYY4sRe9itRk3PJpquJOjeIkz885CczcI4IvJJDLPS72oowuSh+pBxUFROpX+TU++hxhZQ==";
      };
    };
    "parse-json-4.0.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-4.0.0.tgz";
        sha512 = "aOIos8bujGN93/8Ox/jPLh7RwVnPEysynVFE+fQZyg6jKELEHwzgKdLRFHUgXJL6kylijVSBC4BvN9OmsB48Rw==";
      };
    };
    "path-key-2.0.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-2.0.1.tgz";
        sha512 = "fEHGKCSmUSDPv4uoj8AlD+joPlq3peND+HRYyxFz4KPw4z926S/b8rIuFs2FYJg3BwsxJf6A9/3eIdLaYC+9Dw==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "path-type-3.0.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-3.0.0.tgz";
        sha512 = "T2ZUsdZFHgA3u4e5PfPbjd7HDDpxPnQb5jN0SrDsjNSuVXHJqtwTnWqG0B1jZrgmJ/7lj1EmVIByWt1gxGkWvg==";
      };
    };
    "pidtree-0.3.1" = {
      name = "pidtree";
      packageName = "pidtree";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pidtree/-/pidtree-0.3.1.tgz";
        sha512 = "qQbW94hLHEqCg7nhby4yRC7G2+jYHY4Rguc2bjw7Uug4GIJuu1tvf2uHaZv5Q8zdt+WKJ6qK1FOI6amaWUo5FA==";
      };
    };
    "pify-3.0.0" = {
      name = "pify";
      packageName = "pify";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-3.0.0.tgz";
        sha512 = "C3FsVNH1udSEX48gGX1xfvwTWfsYWj5U+8/uK15BGzIGrKoUpghX8hWZwa/OFnakBiiVNmBvemTJR5mcy7iPcg==";
      };
    };
    "prettier-2.8.4" = {
      name = "prettier";
      packageName = "prettier";
      version = "2.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-2.8.4.tgz";
        sha512 = "vIS4Rlc2FNh0BySk3Wkd6xmwxB0FpOndW5fisM5H8hsZSxU2VWVB5CWIkIjWvrHjIhxk2g3bfMKM87zNTrZddw==";
      };
    };
    "read-pkg-3.0.0" = {
      name = "read-pkg";
      packageName = "read-pkg";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg/-/read-pkg-3.0.0.tgz";
        sha512 = "BLq/cCO9two+lBgiTYNqD6GdtK8s4NpaWrl6/rCO9w0TUS8oJl7cmToOZfRYllKTISY6nt1U7jQ53brmKqY6BA==";
      };
    };
    "regexp.prototype.flags-1.4.3" = {
      name = "regexp.prototype.flags";
      packageName = "regexp.prototype.flags";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexp.prototype.flags/-/regexp.prototype.flags-1.4.3.tgz";
        sha512 = "fjggEOO3slI6Wvgjwflkc4NFRCTZAu5CnNfBd5qOMYhWdn67nJBBu34/TkD++eeFmd8C9r9jfXJ27+nSiRkSUA==";
      };
    };
    "resolve-1.22.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.1.tgz";
        sha512 = "nBpuuYuY5jFsli/JIs1oldw6fOQCBioohqWZg/2hiaOybXOft4lonv85uDOKXdf8rhyK159cxU5cDcK/NKk8zw==";
      };
    };
    "safe-regex-test-1.0.0" = {
      name = "safe-regex-test";
      packageName = "safe-regex-test";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-regex-test/-/safe-regex-test-1.0.0.tgz";
        sha512 = "JBUUzyOgEwXQY1NuPtvcj/qcBDbDmEvWufhlnXZIm75DEHp+afM1r1ujJpJsV/gSM4t59tpDyPi1sd6ZaPFfsA==";
      };
    };
    "semver-5.7.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.1.tgz";
        sha512 = "sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==";
      };
    };
    "shebang-command-1.2.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-1.2.0.tgz";
        sha512 = "EV3L1+UQWGor21OmnvojK36mhg+TyIKDh3iFBKBohr5xeXIhNBcx8oWdgkTEEQ+BEFFYdLRuqMfd5L84N1V5Vg==";
      };
    };
    "shebang-regex-1.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz";
        sha512 = "wpoSFAxys6b2a2wHZ1XpDSgD7N9iVjg29Ph9uV/uaP9Ex/KXlkTZTeddxDPSYQpgvzKLGJke2UU0AzoGCjNIvQ==";
      };
    };
    "shell-quote-1.8.0" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-1.8.0.tgz";
        sha512 = "QHsz8GgQIGKlRi24yFc6a6lN69Idnx634w49ay6+jA5yFh7a1UY+4Rp6HPx/L/1zcEDPEij8cIsiqR6bQsE5VQ==";
      };
    };
    "side-channel-1.0.4" = {
      name = "side-channel";
      packageName = "side-channel";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/side-channel/-/side-channel-1.0.4.tgz";
        sha512 = "q5XPytqFEIKHkGdiMIrY10mvLRvnQh42/+GoBlFW3b2LXLE2xxJpZFdm94we0BaoV3RwJyGqg5wS7epxTv0Zvw==";
      };
    };
    "spdx-correct-3.2.0" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-3.2.0.tgz";
        sha512 = "kN9dJbvnySHULIluDHy32WHRUu3Og7B9sbY7tsFLctQkIqnMh3hErYgdMjTYuqmcXX+lK5T1lnUt3G7zNswmZA==";
      };
    };
    "spdx-exceptions-2.3.0" = {
      name = "spdx-exceptions";
      packageName = "spdx-exceptions";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-exceptions/-/spdx-exceptions-2.3.0.tgz";
        sha512 = "/tTrYOC7PPI1nUAgx34hUpqXuyJG+DTHJTnIULG4rDygi4xu/tfgmq1e1cIRwRzwZgo4NLySi+ricLkZkw4i5A==";
      };
    };
    "spdx-expression-parse-3.0.1" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-3.0.1.tgz";
        sha512 = "cbqHunsQWnJNE6KhVSMsMeH5H/L9EpymbzqTQ3uLwNCLZ1Q481oWaofqH7nO6V07xlXwY6PhQdQ2IedWx/ZK4Q==";
      };
    };
    "spdx-license-ids-3.0.12" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "3.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-3.0.12.tgz";
        sha512 = "rr+VVSXtRhO4OHbXUiAF7xW3Bo9DuuF6C5jH+q/x15j2jniycgKbxU09Hr0WqlSLUs4i4ltHGXqTe7VHclYWyA==";
      };
    };
    "string.prototype.padend-3.1.4" = {
      name = "string.prototype.padend";
      packageName = "string.prototype.padend";
      version = "3.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.padend/-/string.prototype.padend-3.1.4.tgz";
        sha512 = "67otBXoksdjsnXXRUq+KMVTdlVRZ2af422Y0aTyTjVaoQkGr3mxl2Bc5emi7dOQ3OGVVQQskmLEWwFXwommpNw==";
      };
    };
    "string.prototype.trimend-1.0.6" = {
      name = "string.prototype.trimend";
      packageName = "string.prototype.trimend";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimend/-/string.prototype.trimend-1.0.6.tgz";
        sha512 = "JySq+4mrPf9EsDBEDYMOb/lM7XQLulwg5R/m1r0PXEFqrV0qHvl58sdTilSXtKOflCsK2E8jxf+GKC0T07RWwQ==";
      };
    };
    "string.prototype.trimstart-1.0.6" = {
      name = "string.prototype.trimstart";
      packageName = "string.prototype.trimstart";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimstart/-/string.prototype.trimstart-1.0.6.tgz";
        sha512 = "omqjMDaY92pbn5HOX7f9IccLA+U1tA9GvtU4JrodiXFfYB7jPzzHpRzpglLAjtUV6bB557zwClJezTqnAiYnQA==";
      };
    };
    "strip-bom-3.0.0" = {
      name = "strip-bom";
      packageName = "strip-bom";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-bom/-/strip-bom-3.0.0.tgz";
        sha512 = "vavAMRXOgBVNF6nyEEmL3DBK19iRpDcoIwW+swQ+CbGiu7lju6t+JklA1MHweoWtadgt4ISVUsXLyDq34ddcwA==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "typed-array-length-1.0.4" = {
      name = "typed-array-length";
      packageName = "typed-array-length";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-array-length/-/typed-array-length-1.0.4.tgz";
        sha512 = "KjZypGq+I/H7HI5HlOoGHkWUUGq+Q0TPhQurLbyrVrvnKTBgzLhIJ7j6J/XTQOi0d1RjyZ0wdas8bKs2p0x3Ng==";
      };
    };
    "typescript-4.9.5" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.9.5.tgz";
        sha512 = "1FXk9E2Hm+QzZQ7z+McJiHL4NW1F2EzMu9Nq9i3zAaGqibafqYwCVU6WyWAuyQRRzOlxou8xZSyXLEN8oKj24g==";
      };
    };
    "unbox-primitive-1.0.2" = {
      name = "unbox-primitive";
      packageName = "unbox-primitive";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unbox-primitive/-/unbox-primitive-1.0.2.tgz";
        sha512 = "61pPlCD9h51VoreyJ0BReideM3MDKMKnh6+V9L08331ipq6Q8OFXZYiqP6n/tbHx4s5I9uRhcye6BrbkizkBDw==";
      };
    };
    "uuid-3.4.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz";
        sha512 = "HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A==";
      };
    };
    "validate-npm-package-license-3.0.4" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.4.tgz";
        sha512 = "DpKm2Ui/xN7/HQKCtpZxoRWBhZ9Z0kqtygG8XCgNQ8ZlDnxuQmWhj566j8fN4Cu3/JmbhsDo7fcAJq4s9h27Ew==";
      };
    };
    "vscode-jsonrpc-8.1.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.1.0.tgz";
        sha512 = "6TDy/abTQk+zDGYazgbIPc+4JoXdwC8NHU9Pbn4UJP1fehUyZmM4RHp5IthX7A6L5KS30PRui+j+tbbMMMafdw==";
      };
    };
    "vscode-languageserver-8.1.0" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-8.1.0.tgz";
        sha512 = "eUt8f1z2N2IEUDBsKaNapkz7jl5QpskN2Y0G01T/ItMxBxw1fJwvtySGB9QMecatne8jFIWJGWI61dWjyTLQsw==";
      };
    };
    "vscode-languageserver-protocol-3.17.3" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.3.tgz";
        sha512 = "924/h0AqsMtA5yK22GgMtCYiMdCOtWTSGgUOkgEDX+wk2b0x4sAfLiO4NxBxqbiVtz7K7/1/RgVrVI0NClZwqA==";
      };
    };
    "vscode-languageserver-textdocument-1.0.9" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.9.tgz";
        sha512 = "NPfHVGFW2/fQEWHspr8x3PXhRgtFbuDZdl7p6ifuN3M7nk2Yjf5POr/NfDBuAiQG88DehDyJ7nGOT+p+edEtbw==";
      };
    };
    "vscode-languageserver-types-3.17.3" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.3.tgz";
        sha512 = "SYU4z1dL0PyIMd4Vj8YOqFvHu7Hz/enbWtpfnVbJHU4Nd1YNYx8u0ennumc6h48GQNeOLxmwySmnADouT/AuZA==";
      };
    };
    "vscode-uri-2.1.2" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-2.1.2.tgz";
        sha512 = "8TEXQxlldWAuIODdukIb+TR5s+9Ds40eSJrw+1iDDA9IFORPjMELarNQE3myz5XIkWWpdprmJjm1/SxMlWOC8A==";
      };
    };
    "which-1.3.1" = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "which-boxed-primitive-1.0.2" = {
      name = "which-boxed-primitive";
      packageName = "which-boxed-primitive";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-boxed-primitive/-/which-boxed-primitive-1.0.2.tgz";
        sha512 = "bwZdv0AKLpplFY2KZRX6TvyuN7ojjr7lwkg6ml0roIy9YeuSr7JS372qlNW18UQYzgYK9ziGcerWqZOmEn9VNg==";
      };
    };
    "which-typed-array-1.1.9" = {
      name = "which-typed-array";
      packageName = "which-typed-array";
      version = "1.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-typed-array/-/which-typed-array-1.1.9.tgz";
        sha512 = "w9c4xkx6mPidwp7180ckYWfMmvxpjlZuIudNtDf4N/tTAUB8VJbX25qZoAsrtGuYNnGw3pa0AXgbGKRB8/EceA==";
      };
    };
  };
in
{
  purescript-language-server = nodeEnv.buildNodePackage {
    name = "purescript-language-server";
    packageName = "purescript-language-server";
    version = "0.17.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/purescript-language-server/-/purescript-language-server-0.17.1.tgz";
      sha512 = "o/YpvFMOXp5/UqfFjed8+pwZwttg1QpI3iqkHlMB16AW8MRYGVwTAw1zV8MGqazFFat5j3+IJEUHhaeFON0EfA==";
    };
    dependencies = [
      sources."@rowtype-yoga/prettier-plugin-purescript-1.11.2"
      sources."@types/node-16.18.14"
      sources."ansi-styles-3.2.1"
      sources."available-typed-arrays-1.0.5"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."call-bind-1.0.2"
      sources."chalk-2.4.2"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."concat-map-0.0.1"
      (sources."cross-spawn-6.0.5" // {
        dependencies = [
          sources."which-1.3.1"
        ];
      })
      sources."define-properties-1.2.0"
      sources."error-ex-1.3.2"
      sources."es-abstract-1.21.1"
      sources."es-set-tostringtag-2.0.1"
      sources."es-to-primitive-1.2.1"
      sources."esbuild-0.13.15"
      sources."esbuild-android-arm64-0.13.15"
      sources."esbuild-darwin-64-0.13.15"
      sources."esbuild-darwin-arm64-0.13.15"
      sources."esbuild-freebsd-64-0.13.15"
      sources."esbuild-freebsd-arm64-0.13.15"
      sources."esbuild-linux-32-0.13.15"
      sources."esbuild-linux-64-0.13.15"
      sources."esbuild-linux-arm-0.13.15"
      sources."esbuild-linux-arm64-0.13.15"
      sources."esbuild-linux-mips64le-0.13.15"
      sources."esbuild-linux-ppc64le-0.13.15"
      sources."esbuild-netbsd-64-0.13.15"
      sources."esbuild-openbsd-64-0.13.15"
      sources."esbuild-sunos-64-0.13.15"
      sources."esbuild-windows-32-0.13.15"
      sources."esbuild-windows-64-0.13.15"
      sources."esbuild-windows-arm64-0.13.15"
      sources."escape-string-regexp-1.0.5"
      sources."for-each-0.3.3"
      sources."function-bind-1.1.1"
      sources."function.prototype.name-1.1.5"
      sources."functions-have-names-1.2.3"
      sources."get-intrinsic-1.2.0"
      sources."get-symbol-description-1.0.0"
      sources."globalthis-1.0.3"
      sources."gopd-1.0.1"
      sources."graceful-fs-4.2.10"
      sources."has-1.0.3"
      sources."has-bigints-1.0.2"
      sources."has-flag-3.0.0"
      sources."has-property-descriptors-1.0.0"
      sources."has-proto-1.0.1"
      sources."has-symbols-1.0.3"
      sources."has-tostringtag-1.0.0"
      sources."hosted-git-info-2.8.9"
      sources."internal-slot-1.0.5"
      sources."is-array-buffer-3.0.2"
      sources."is-arrayish-0.2.1"
      sources."is-bigint-1.0.4"
      sources."is-boolean-object-1.1.2"
      sources."is-callable-1.2.7"
      sources."is-core-module-2.11.0"
      sources."is-date-object-1.0.5"
      sources."is-negative-zero-2.0.2"
      sources."is-number-object-1.0.7"
      sources."is-regex-1.1.4"
      sources."is-shared-array-buffer-1.0.2"
      sources."is-string-1.0.7"
      sources."is-symbol-1.0.4"
      sources."is-typed-array-1.1.10"
      sources."is-weakref-1.0.2"
      sources."isexe-2.0.0"
      sources."json-parse-better-errors-1.0.2"
      sources."load-json-file-4.0.0"
      sources."memorystream-0.3.1"
      sources."minimatch-3.1.2"
      sources."nice-try-1.0.5"
      sources."normalize-package-data-2.5.0"
      sources."npm-run-all-4.1.5"
      sources."object-inspect-1.12.3"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.4"
      sources."parse-json-4.0.0"
      sources."path-key-2.0.1"
      sources."path-parse-1.0.7"
      sources."path-type-3.0.0"
      sources."pidtree-0.3.1"
      sources."pify-3.0.0"
      sources."prettier-2.8.4"
      sources."read-pkg-3.0.0"
      sources."regexp.prototype.flags-1.4.3"
      sources."resolve-1.22.1"
      sources."safe-regex-test-1.0.0"
      sources."semver-5.7.1"
      sources."shebang-command-1.2.0"
      sources."shebang-regex-1.0.0"
      sources."shell-quote-1.8.0"
      sources."side-channel-1.0.4"
      sources."spdx-correct-3.2.0"
      sources."spdx-exceptions-2.3.0"
      sources."spdx-expression-parse-3.0.1"
      sources."spdx-license-ids-3.0.12"
      sources."string.prototype.padend-3.1.4"
      sources."string.prototype.trimend-1.0.6"
      sources."string.prototype.trimstart-1.0.6"
      sources."strip-bom-3.0.0"
      sources."supports-color-5.5.0"
      sources."supports-preserve-symlinks-flag-1.0.0"
      sources."typed-array-length-1.0.4"
      sources."typescript-4.9.5"
      sources."unbox-primitive-1.0.2"
      sources."uuid-3.4.0"
      sources."validate-npm-package-license-3.0.4"
      sources."vscode-jsonrpc-8.1.0"
      sources."vscode-languageserver-8.1.0"
      sources."vscode-languageserver-protocol-3.17.3"
      sources."vscode-languageserver-textdocument-1.0.9"
      sources."vscode-languageserver-types-3.17.3"
      sources."vscode-uri-2.1.2"
      sources."which-2.0.2"
      sources."which-boxed-primitive-1.0.2"
      sources."which-typed-array-1.1.9"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Language Server Protocol server for PureScript wrapping purs ide server functionality";
      homepage = "https://github.com/nwolverson/purescript-language-server";
      license = "MIT";
    };
    production = false;
    bypassCache = true;
    reconstructLock = true;
  };
}
